go_install_targets:
  - github.com/air-verse/air@latest
  - github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  - go.uber.org/mock/mockgen@latest
  - golang.org/x/tools/gopls@latest
  - github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
