formulas:
  - actionlint
  - argocd
  - aws-sam-cli
  - awscli
  - azure-cli
  - buf
  - coreutils
  - codex
  - ffmpeg
  - gemini-cli
  - gh
  - git
  - helm
  - jq
  - k9s
  - kubectl
  - kustomize
  - minikube
  - mise
  - mysql
  - oapi-codegen
  - packer
  - postgresql
  - redis
  - starship
  - sqlite
  - watch
  - yamlfmt
  - yamllint
  - zsh
  - zsh-completions

casks:
  - 1password
  - appcleaner
  - aws-vpn-client
  - claude-code
  - deepl
  - discord
  - displaylink
  - docker-desktop
  - elgato-game-capture-hd
  - firefox
  - font-fira-code-nerd-font
  - font-hack-nerd-font
  - font-ricty-diminished
  - gcloud-cli
  - google-japanese-ime
  - imageoptim
  - karabiner-elements
  - kiro-cli
  - loopback
  - mongosh
  - ngrok
  - notion
  - notion-calendar
  - postman
  - raycast
  - slack
  - tradingview
  - tunnelbear
  - tunnelblick
  - visual-studio-code
  - visual-studio-code@insiders
  - zoom
